### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by qzqs** [TakWolf/Readhub-Android#3]
你好，为什么我下载下来导入AS就提示我找到Api23呢？
C:\Users\Administrator\Desktop\AllNetDemo\Readhub\Readhub\app\src\main\java\me\readhub\android\md\ui\base\BaseActivity.java
Error:(9, 17) 错误: 无法访问ActivityCompatApi23
找不到android.support.v4.app.ActivityCompatApi23的类文件
我又导入了v4包，还是不行，导致了所有的类都找不到v4包的方法

**Comment by TakWolf** [comment]
是哪个结点？

这个项目应该不会出问题啊
这个项目是个 真 干净无依赖的项目

**Comment by TakWolf** [comment]
环境还是 Android Studio 2.3.3 吗？

最新节点代码，先检查构建配置：
google 仓库 ， dependencies 写法
然后 support 退回到 25 试一下

**Comment by qzqs** [comment]
对的，还是2.3.3 ，已经构建配置了，google仓库也像CNode一样调整了，dependencies 也调整为compile， support 退回到 25  还是一样的错误，不是很明白为什么这样

**Comment by TakWolf** [comment]
本地sdk下载了 support 吗？
25.x 之前需要在本地下载

还不行，就试试 tag 1.1.0 这个节点，这个是 2.3.3 环境的

这个项目环境是干净的，应该不会出问题。所有我也不知道你的原因是什么。
